#!/bin/bash

INSTALL_ROOT=$PWD
CGAL_ROOT=${INSTALL_ROOT}/external/cgal


cd $CGAL_ROOT
#cmake -G "Visual Studio 15 2017 Win64" -T host=x64 .
./scripts/cgal_create_CMakeLists -s executable
cd $INSTALL_ROOT

#cd D:/src/blenditor/external/cgal/Kernel_23
cmake -G "Visual Studio 15 2017 Win64" -T host=x64 \
    -D CGAL_DIR=$CGAL_ROOT \
    -D CMAKE_MODULE_PATH="$CGAL_ROOT/cmake/modules" \
    -D WITH_CGAL_Core=1 \
    -D WITH_CGAL_Qt5=0 \
    -D WITH_CGAL_ImageIO=0 \
    -D WITH_GMP=1 \
    -D GMP_INCLUDE_DIR="${CGAL_ROOT}/auxiliary/gmp/include/" \
    -D GMP_LIBRARIES="${CGAL_ROOT}/auxiliary/gmp/lib/libgmp-10.lib" \
    -D WITH_MPFR=1 \
    -D MPFR_INCLUDE_DIR="${CGAL_ROOT}/auxiliary/gmp/include/" \
    -D MPFR_LIBRARIES="${CGAL_ROOT}/auxiliary/gmp/lib/libmpfr-4.lib" \
    -D BOOST_ROOT="${CGAL_ROOT}/auxiliary/boost/" \
    -D Boost_ROOT="${CGAL_ROOT}/auxiliary/boost/" \
    -D BOOST_INCLUDE_DIR="${CGAL_ROOT}/auxiliary/boost/boost/" \
    -D Boost_INCLUDE_DIR="${CGAL_ROOT}/auxiliary/boost/boost/" \
    .