#!/bin/sh

#    Copyright (C) 2018  Scott Checko. All Rights Reserved.

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


MAIN=source/main.py
DATA=data/test.blend

COMMAND=$1

if [[ $COMMAND = "editor" ]]; then
    blender --python $MAIN $DATA 
elif [[ $COMMAND = "back" ]]; then
    blender --background --python $MAIN $DATA
fi